language: php
php:
  - 7
before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;
  - phpenv config-add tests/config.ini
install:
  - composer install
script:
  - vendor/bin/phpunit
