language: php
php:
  - 7
  - hhvm
before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;
install:
  - composer install
before_script:
  - phpenv config-add tests/config.ini
script:
  - vendor/bin/phpunit
