name: CI
on:
  - pull_request
  - push
jobs:
  phpunit:
    name: "PHPUnit (PHP: ${{ matrix.php-versions }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
         - 8.0
         - 8.1
    services:
      mongo:
        image: mongo:5.0
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: test1234
          MONGO_INITDB_DATABASE: fusio
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run PHPUnit
        run: vendor/bin/phpunit
